-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'PRODUCT_PUBLISH';
ALTER TYPE "AuditAction" ADD VALUE 'PRODUCT_DEACTIVATE';
ALTER TYPE "AuditAction" ADD VALUE 'PRODUCT_ARCHIVE';
ALTER TYPE "AuditAction" ADD VALUE 'PRODUCT_RESTORE';